<?php foreach ($this->addresses as $address) : ?>

<?php

$params = http_build_query(array(
    'markers' => '|' . $address->getStreetAddress() . ' ' . $address->getCity() . ', ' . $address->getProvince(),
    'sensor' => 'false',
    'size' => '150x150'
));

$imgurl = "http://maps.googleapis.com/maps/api/staticmap?" . $params;

?>

<div style="float: left; margin-right: 10px;">
    <img src="<?=$imgurl?>" />
</div>
<p><em><?=$address->getName()?></em><br />
<?=$address->getStreetAddress()?><br />
<?=$address->getCity()?>, <?=$address->getProvince()?> <?=$address->getPostalCode()?><br />
<?=$address->getCountry()?></p>
<?php $editUrl = $this->url('address/edit/query', array('id' => $address->getAddressId())); ?>
<?php $deleteUrl = $this->url('address/delete/query', array('id' => $address->getAddressId())); ?>
<a href="<?=$editUrl?>">Edit</a> &middot; <a href="<?=$deleteUrl?>">Delete</a>
<p style="clear: both"></p>
<?php endforeach; ?>
<a href="<?=$this->url('address/add')?>">Add Address</a>
